# Generated by Django 4.2.6 on 2023-11-09 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apunte'),
    ]

    operations = [
        migrations.AddField(
            model_name='apunte',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 10, 22, 51, 575963)),
        ),
        migrations.AddField(
            model_name='examen',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 10, 22, 51, 533261)),
        ),
    ]
